### ISSUE TITLE
c3D file import failure

### ISSUE THREAD

**Issue by TheDiexX** [MattiasFredriksson/io_anim_c3d#15]
Good morning,
I have a c3D file import failure.
blender puts as error:  " Failed to load any of the .bvh files(s):" and the source .
can you help me please?

thank you

**Comment by VineetTambe** [comment]
Facing the same error! 
Were you able to resolve it?

**Comment by VineetTambe** [comment]
A [version](https://github.com/VineetTambe/io_anim_c3d) that works with Blender 4.1

**Comment by MattiasFredriksson** [comment]
Should be resolved with the updated version found in: https://github.com/MattiasFredriksson/io_anim_c3d/releases/tag/v2.0.0
