### ISSUE TITLE
Cannot export to c3d

### ISSUE THREAD

**Issue by MasterHansCoding** [MattiasFredriksson/io_anim_c3d#5]
I succeeded to install this addon. The file/import/c3d got enabled, but not the file/export/c3d :(

Is it normal ? I am using Blender 3.1

Thanks !

**Comment by MattiasFredriksson** [comment]
Sorry, exporting c3d files is currently not supported. I have imlemented features for writing .c3d files in the project used to parse the files so an exporter might be relevant at some point. With those changes still under review and documentation/tests being the next step for this project it will take some time before an exporter would become relevant however.

**Comment by MattiasFredriksson** [comment]
Closing this issue as it is closer to a feature request/documentation limitation rather than an implementation issue.
